/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IntegratorRouteImport } from './routes/integrator'
import { Route as ApiSlotSplatRouteImport } from './routes/api/slot/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegratorRoute = IntegratorRouteImport.update({
  id: '/integrator',
  path: '/integrator',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSlotSplatRoute = ApiSlotSplatRouteImport.update({
  id: '/api/slot/$',
  path: '/api/slot/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/integrator': typeof IntegratorRoute
  '/api/slot/$': typeof ApiSlotSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/integrator': typeof IntegratorRoute
  '/api/slot/$': typeof ApiSlotSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/integrator': typeof IntegratorRoute
  '/api/slot/$': typeof ApiSlotSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/integrator' | '/api/slot/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/integrator' | '/api/slot/$'
  id: '__root__' | '/' | '/integrator' | '/api/slot/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IntegratorRoute: typeof IntegratorRoute
  ApiSlotSplatRoute: typeof ApiSlotSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrator': {
      id: '/integrator'
      path: '/integrator'
      fullPath: '/integrator'
      preLoaderRoute: typeof IntegratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/slot/$': {
      id: '/api/slot/$'
      path: '/api/slot/$'
      fullPath: '/api/slot/$'
      preLoaderRoute: typeof ApiSlotSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IntegratorRoute: IntegratorRoute,
  ApiSlotSplatRoute: ApiSlotSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
